name: Gatsby Build
on: 
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - 'main'
jobs:
  AuditDependencies:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v2
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_pr_comments: true
          dedupe_issues: true
  BuildSite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Run Gatsby Build
        run: npx gatsby build
