name: Gatsby Build
on: 
  pull_request:
    types: [opened, edited, synchronize]
  push:
    branches:
      - 'main'
jobs:
  BuildSite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install --prod --pure-lockfile
      - name: Run Gatsby Build
        run: npx gatsby build
